name: Scheduled WhatsApp Profile Picture Update

on:
  workflow_dispatch: {}

jobs:
  update-pfp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Dependencies
        run: npm install

      - name: Run Script with Environment Secret
        env:
          WHATSAPP_SESSION: ${{ secrets.WHATSAPP_SESSION }}
        run: node scripts/script.js
