name: Run Scheduled JS Script

on:
  schedule:
    # Runs daily at 4:00 AM, 8:00 AM, and 7:00 PM IST
    - cron: "30 22 * * *" # 4:00 AM IST (22:30 UTC)
    - cron: "30 2 * * *" # 8:00 AM IST (02:30 UTC)
    - cron: "30 13 * * *" # 7:00 PM IST (13:30 UTC)
  workflow_dispatch:

jobs:
  run-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run JavaScript script
        run: node scripts/script.js
