name: Scheduled WhatsApp Profile Picture Update

on:
  schedule:
    # 4:00 AM IST (22:30 UTC)
    - cron: "30 22 * * *"
    # 8:00 AM IST (02:30 UTC)
    - cron: "30 2 * * *"
    # 7:00 PM IST (13:30 UTC)
    - cron: "30 13 * * *"
  workflow_dispatch: {}

jobs:
  update-pfp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Run Script with Environment Secret
        env:
          WHATSAPP_SESSION: ${{ secrets.WHATSAPP_SESSION }}
        run: scritps/script.js
